kafkaPool: nav-dev
replicas:
  min: "1"
  max: "1"
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    rules:
      - application: sykepengesoknad-backend
        namespace: flex
        cluster: dev-gcp
env:
  - name: SOKNAD_API_URL
    value: http://sykepengesoknad-backend.flex
  - name: ACCESS_TOKEN_SCOPE
    value: api://dev-gcp.flex.sykepengesoknad-backend/.default