kafkaPool: nav-prod
replicas:
  max: "12"
limits:
  cpu: 2000m
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: sykepengesoknad-backend
        namespace: flex
        cluster: prod-gcp
      - application: spinosaurus
        namespace: helsearbeidsgiver
        cluster: prod-gcp
env:
  - name: SOKNAD_API_URL
    value: http://sykepengesoknad-backend.flex
  - name: ACCESS_TOKEN_SCOPE
    value: api://prod-gcp.flex.sykepengesoknad-backend/.default
  - name: IM_API_URL
    value: http://spinosaurus.helsearbeidsgiver
  - name: ACCESS_TOKEN_SCOPE_IM
    value: api://prod-gcp.helsearbeidsgiver.spinosaurus/.default