kafkaPool: nav-prod
replicas:
  min: "1"
  max: "12"
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: sykepengesoknad-backend
        namespace: flex
        cluster: prod-gcp
    external:
      - host: syfoinntektsmelding.dev-fss-pub.nais.io
env:
  - name: SOKNAD_API_URL
    value: http://sykepengesoknad-backend.flex
  - name: ACCESS_TOKEN_SCOPE
    value: api://prod-gcp.flex.sykepengesoknad-backend/.default
  - name: IM_API_URL
    value: https://syfoinntektsmelding.dev-fss-pub.nais.io
  - name: ACCESS_TOKEN_SCOPE_IM
    value: api://dev-fss.helsearbeidsgiver.syfoinntektsmelding/.default