CREATE TABLE IF_FKONTO_12
(
    IF01_KODE        CHAR(1 CHAR)      NULL,
    IF01_AGNR_FNR    NUMBER(11, 0)     NULL,
    IF10_FORSFOM_SEQ NUMBER(8, 0)      NULL,
    IF12_BETDATO_SEQ NUMBER(8, 0)      NULL,
    IF12_FOM         NUMBER(8, 0)      NULL,
    IF12_TOM         NUMBER(8, 0)      NULL,
    IF12_BET_KODE    CHAR(1 CHAR)      NULL,
    IF12_FRIUKER     CHAR(2 CHAR)      NULL,
    IF12_BELOEP      NUMBER(7, 2)      NULL,
    IF12_BETDATO     NUMBER(8, 0)      NULL,
    OPPRETTET        TIMESTAMP(6)      NOT NULL,
    ENDRET_I_KILDE   TIMESTAMP(6)      NOT NULL,
    KILDE_IF         VARCHAR2(12 CHAR) NOT NULL,
    ID_KONT          NUMBER            NOT NULL,
    OPPDATERT        TIMESTAMP(6)      NULL
)
