
package no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.binding;

import no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.feil.AktoerIkkeFunnet;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "finnMeldekortUtbetalingsgrunnlagListeaktoerIkkeFunnet", targetNamespace = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1")
public class FinnMeldekortUtbetalingsgrunnlagListeAktoerIkkeFunnet
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AktoerIkkeFunnet faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FinnMeldekortUtbetalingsgrunnlagListeAktoerIkkeFunnet(String message, AktoerIkkeFunnet faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FinnMeldekortUtbetalingsgrunnlagListeAktoerIkkeFunnet(String message, AktoerIkkeFunnet faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.feil.AktoerIkkeFunnet
     */
    public AktoerIkkeFunnet getFaultInfo() {
        return faultInfo;
    }

}
