
package no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.binding;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeldekortUtbetalingsgrunnlag_v1", targetNamespace = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/Binding", wsdlLocation = "file:/home/runner/work/tjenestespesifikasjoner/tjenestespesifikasjoner/nav-meldekortUtbetalingsgrunnlag-v1-tjenestespesifikasjon/src/main/wsdl/no/nav/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/Binding.wsdl")
public class MeldekortUtbetalingsgrunnlagV1_Service
    extends Service
{

    private final static URL MELDEKORTUTBETALINGSGRUNNLAGV1_WSDL_LOCATION;
    private final static WebServiceException MELDEKORTUTBETALINGSGRUNNLAGV1_EXCEPTION;
    private final static QName MELDEKORTUTBETALINGSGRUNNLAGV1_QNAME = new QName("http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/Binding", "MeldekortUtbetalingsgrunnlag_v1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/runner/work/tjenestespesifikasjoner/tjenestespesifikasjoner/nav-meldekortUtbetalingsgrunnlag-v1-tjenestespesifikasjon/src/main/wsdl/no/nav/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/Binding.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MELDEKORTUTBETALINGSGRUNNLAGV1_WSDL_LOCATION = url;
        MELDEKORTUTBETALINGSGRUNNLAGV1_EXCEPTION = e;
    }

    public MeldekortUtbetalingsgrunnlagV1_Service() {
        super(__getWsdlLocation(), MELDEKORTUTBETALINGSGRUNNLAGV1_QNAME);
    }

    public MeldekortUtbetalingsgrunnlagV1_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MELDEKORTUTBETALINGSGRUNNLAGV1_QNAME, features);
    }

    public MeldekortUtbetalingsgrunnlagV1_Service(URL wsdlLocation) {
        super(wsdlLocation, MELDEKORTUTBETALINGSGRUNNLAGV1_QNAME);
    }

    public MeldekortUtbetalingsgrunnlagV1_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MELDEKORTUTBETALINGSGRUNNLAGV1_QNAME, features);
    }

    public MeldekortUtbetalingsgrunnlagV1_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeldekortUtbetalingsgrunnlagV1_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeldekortUtbetalingsgrunnlagV1
     */
    @WebEndpoint(name = "meldekortUtbetalingsgrunnlag_v1Port")
    public MeldekortUtbetalingsgrunnlagV1 getMeldekortUtbetalingsgrunnlagV1Port() {
        return super.getPort(new QName("http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/Binding", "meldekortUtbetalingsgrunnlag_v1Port"), MeldekortUtbetalingsgrunnlagV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeldekortUtbetalingsgrunnlagV1
     */
    @WebEndpoint(name = "meldekortUtbetalingsgrunnlag_v1Port")
    public MeldekortUtbetalingsgrunnlagV1 getMeldekortUtbetalingsgrunnlagV1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/Binding", "meldekortUtbetalingsgrunnlag_v1Port"), MeldekortUtbetalingsgrunnlagV1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MELDEKORTUTBETALINGSGRUNNLAGV1_EXCEPTION!= null) {
            throw MELDEKORTUTBETALINGSGRUNNLAGV1_EXCEPTION;
        }
        return MELDEKORTUTBETALINGSGRUNNLAGV1_WSDL_LOCATION;
    }

}
