
package no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.binding;

import no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.feil.ObjectFactory;
import no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.meldinger.FinnMeldekortUtbetalingsgrunnlagListeRequest;
import no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.meldinger.FinnMeldekortUtbetalingsgrunnlagListeResponse;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "meldekortUtbetalingsgrunnlag_v1", targetNamespace = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1")
@XmlSeeAlso({
    no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.ObjectFactory.class,
    ObjectFactory.class,
    no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.informasjon.ObjectFactory.class,
    no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.meldinger.ObjectFactory.class
})
public interface MeldekortUtbetalingsgrunnlagV1 {


    /**
     * 
     * @param request
     * @return
     *     returns no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.meldinger.FinnMeldekortUtbetalingsgrunnlagListeResponse
     * @throws FinnMeldekortUtbetalingsgrunnlagListeUgyldigInput
     * @throws FinnMeldekortUtbetalingsgrunnlagListeSikkerhetsbegrensning
     * @throws FinnMeldekortUtbetalingsgrunnlagListeAktoerIkkeFunnet
     */
    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/meldekortUtbetalingsgrunnlag_v1/finnMeldekortUtbetalingsgrunnlagListeRequest")
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "finnMeldekortUtbetalingsgrunnlagListe", targetNamespace = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1", className = "no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.FinnMeldekortUtbetalingsgrunnlagListe")
    @ResponseWrapper(localName = "finnMeldekortUtbetalingsgrunnlagListeResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1", className = "no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.FinnMeldekortUtbetalingsgrunnlagListeResponse")
    public FinnMeldekortUtbetalingsgrunnlagListeResponse finnMeldekortUtbetalingsgrunnlagListe(
        @WebParam(name = "request", targetNamespace = "")
        FinnMeldekortUtbetalingsgrunnlagListeRequest request)
        throws FinnMeldekortUtbetalingsgrunnlagListeAktoerIkkeFunnet, FinnMeldekortUtbetalingsgrunnlagListeSikkerhetsbegrensning, FinnMeldekortUtbetalingsgrunnlagListeUgyldigInput
    ;

    /**
     * 
     */
    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1/meldekortUtbetalingsgrunnlag_v1/pingRequest")
    @RequestWrapper(localName = "ping", targetNamespace = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1", className = "no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/meldekortUtbetalingsgrunnlag/v1", className = "no.nav.tjeneste.virksomhet.meldekortutbetalingsgrunnlag.v1.PingResponse")
    public void ping();

}
