kafkaPool: nav-dev
replicas:
  min: "1"
  max: "1"
env:
  - name: STS_BASE_URL
    value: http://security-token-service.default.svc.nais.local
gcp:
  type: POSTGRES_14
  name: sparkelidenter
  envVarPrefix: DATABASE
  tier: db-f1-micro
