kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
env:
  - name: KAFKA_EXTRA_TOPIC
    value: tbd.arbeidsgiveropplysninger
  - name: SEND_FORRIGE_INNTEKT
    value: "true"
gcp:
  type: POSTGRES_15
  name: sparkelarbeidsgiver
  envVarPrefix: DATABASE