kafkaPool: nav-prod
replicas:
  min: 1
  max: 1
limits:
  cpu: 2000m
env:
  - name: KAFKA_EXTRA_TOPIC
    value: tbd.arbeidsgiveropplysninger
gcp:
  type: POSTGRES_15
  name: sparkelarbeidsgiver
  envVarPrefix: DATABASE
  tier: db-custom-1-3840