kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    rules:
      - application: repr-api
        namespace: repr
        cluster: dev-gcp
env:
  - name: REPR_API_URL
    value: http://repr-api.repr
  - name: REPR_API_SCOPE
    value: api://dev-gcp.repr.repr-api/.default
