kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: trygdeetaten.no
accessPolicy:
  inbound:
    rules:
      - application: spoken
        namespace: tbd
        cluster: dev-gcp
  outbound:
    external:
      - host: pdl-fullmakt.dev-fss-pub.nais.io
env:
  - name: PDL_FULLMAKT_URL
    value: https://pdl-fullmakt.dev-fss-pub.nais.io
  - name: PDL_FULLMAKT_SCOPE
    value: api://dev-fss.pdl.pdl-fullmakt/.default
