kafkaPool: nav-prod
replicas:
  min: 2
  max: 2
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: pdl-fullmakt-api
        namespace: repr
env:
  - name: PDL_FULLMAKT_URL
    value: http://pdl-fullmakt-api.repr
  - name: PDL_FULLMAKT_SCOPE
    value: api://prod-gcp:repr:pdl-fullmakt-api/.default
