kafkaPool: nav-prod
replicas:
  min: 2
  max: 2
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    external:
      - host: pdl-fullmakt.prod-fss-pub.nais.io
env:
  - name: PDL_FULLMAKT_URL
    value: https://pdl-fullmakt.prod-fss-pub.nais.io
  - name: PDL_FULLMAKT_SCOPE
    value: api://prod-fss.pdl.pdl-fullmakt/.default
