kafkaPool: nav-prod
replicas:
  min: 2
  max: 2
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: repr-api
        namespace: repr
        cluster: prod-gcp
env:
  - name: REPR_API_URL
    value: http://repr-api.repr
  - name: REPR_API_SCOPE
    value: api://prod-gcp.repr.repr-api/.default
