kafkaPool: nav-prod
cpu:
  max: 2000m
azure:
  enabled: true
accessPolicy:
  outbound:
    rules:
      - application: medlemskap-sykepenger-listener
        namespace: medlemskap
env:
  - name: MEDLEMSKAP_SCOPE
    value: api://prod-gcp.medlemskap.medlemskap-sykepenger-listener/.default
  - name: MEDLEMSKAP_BASE_URL
    value: http://medlemskap-sykepenger-listener.medlemskap.svc.cluster.local
