kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelnorg
env:
- name: NORG2_BASE_URL
  value: https://app-q1.adeo.no/norg2/api/v1
- name: PERSONV3_URL
  value: https://app-q1.adeo.no/tpsws-aura/ws/Person/v3
- name: SECURITY_TOKEN_SERVICE_URL
  value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
