kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
accessPolicy:
  outbound:
    rules:
      - application: speed-api
        namespace: tbd
      - application: norg2
        namespace: org
