kafkaPool: nav-dev
azure:
  enabled: true
  tenant: trygdeetaten.no
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelpleiepenge
env:
- name: AZURE_TENANT_ID
  value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
- name: AZURE_TENANT_BASEURL
  value: https://login.microsoftonline.com
- name: INFOTRYGD_SCOPE
  value: api://32551525-c4dd-44ae-b906-2f8d8a00bb03/.default
- name: INFOTRYGD_URL
  value: http://infotrygd-grunnlag-paaroerende-sykdom.default.svc.nais.local
