kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
limits:
  cpu: 2000m
mountPaths:
  - mountPath: /var/run/secrets/nais.io/oracle/creds
    kvPath: oracle/data/dev/creds/infotrygd_spq-user
  - mountPath: /var/run/secrets/nais.io/oracle/config
    kvPath: oracle/data/dev/config/infotrygd_spq-user
env:
  - name: DATABASE_SCHEMA
    value: INFOTRYGD_SPQ
onprem: true