kafkaPool: nav-prod
replicas:
  min: 1
  max: 2
limits:
  cpu: 2000m
mountPaths:
  - mountPath: /var/run/secrets/nais.io/oracle/creds
    kvPath: oracle/data/prod/creds/sp_infotrygd_p-user
  - mountPath: /var/run/secrets/nais.io/oracle/config
    kvPath: oracle/data/prod/config/infotrygd_spp
env:
  - name: DATABASE_SCHEMA
    value: INFOTRYGD_SPP
onprem: true