kafkaPool: nav-dev
replicas:
  min: "1"
  max: "1"
limits:
  cpu: 2000m
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    external:
      - host: pdl-api.dev-fss-pub.nais.io
env:
  - name: PDL_URL
    value: https://pdl-api.dev-fss-pub.nais.io/graphql
  - name: ACCESS_TOKEN_SCOPE
    value: api://dev-fss.pdl.pdl-api/.default