kafkaPool: nav-dev
replicas:
  min: "1"
  max: "1"
limits:
  cpu: 2000m
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    rules:
      - application: speed-api
        namespace: tbd