kafkaPool: nav-dev
replicas:
  min: "0"
  max: "0"
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: trygdeetaten.no
externalHosts:
  - pdl-api.dev-fss-pub.nais.io
env:
  - name: PDL_URL
    value: https://pdl-api.dev-fss-pub.nais.io/graphql
  - name: ACCESS_TOKEN_SCOPE
    value: api://dev-fss.pdl.pdl-api/.default