kafkaPool: nav-prod
replicas:
  max: "12"
  cpuThresholdPercentage: 500
requests:
  cpu: 100m
  memory: 320Mi
limits:
  memory: 320Mi
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: speed-api
        namespace: tbd