kafkaPool: nav-prod
replicas:
  max: "12"
  cpuThresholdPercentage: 200
cpu:
  min: "100m"
memory:
  min: "320Mi"
  max: "320Mi"
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    external:
      - host: pdl-api.prod-fss-pub.nais.io
env:
  - name: PDL_URL
    value: https://pdl-api.prod-fss-pub.nais.io/graphql
  - name: ACCESS_TOKEN_SCOPE
    value: api://prod-fss.pdl.pdl-api/.default