kafkaPool: nav-prod
replicas:
  max: "12"
  cpuThresholdPercentage: 500
limits:
  cpu: 2000m
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  outbound:
    rules:
      - application: speed-api
        namespace: tbd
