kafkaPool: nav-prod
replicas:
  max: "12"
  cpuThresholdPercentage: 500
requests:
  cpu: 100m
  memory: 320Mi
limits:
  memory: 320Mi
azure:
  enabled: true
  claims:
    extra:
      - azp_name
  tenant: nav.no
accessPolicy:
  inbound:
    rules:
      - application: speed-api
        namespace: tbd
        cluster: prod-gcp
  outbound:
    external:
      - host: pdl-api.prod-fss-pub.nais.io
env:
  - name: PDL_URL
    value: https://pdl-api.prod-fss-pub.nais.io/graphql
  - name: ACCESS_TOKEN_SCOPE
    value: api://prod-fss.pdl.pdl-api/.default