--CREATE SCHEMA IF NOT EXISTS

-- is_inntekt_13 -----------
DROP TABLE IF EXISTS is_inntekt_13;
CREATE TABLE is_inntekt_13
(
    is01_personkey bigint NOT NULL,
    is10_arbufoer_seq integer NOT NULL,
    is13_spfom integer NOT NULL,
    is13_arbgivnr bigint NOT NULL,
    is13_loenn numeric(11,2) NOT NULL,
    is13_periode character(1)   NOT NULL,
    is13_ref character(1)   NOT NULL,
    is13_ref_tom integer NOT NULL,
    is13_gml_spfom integer NOT NULL,
    is13_gml_loenn numeric(11,2) NOT NULL,
    is13_gml_periode character(1)   NOT NULL,
    is13_po_innt character(1)   NOT NULL,
    is13_utbet character(1)   NOT NULL,
    is13_tidskonto_kode character(1)   NOT NULL,
    tk_nr character(4)   NOT NULL,
    f_nr character(11)   NOT NULL,
    opprettet timestamp(6),
    endret_i_kilde timestamp(6),
    kilde_is varchar(12),
    region character(1)   NOT NULL ,
    id_innt double precision NOT NULL
);

-- is_utbetaling_15 --------------
DROP TABLE IF EXISTS is_utbetaling_15;
CREATE TABLE is_utbetaling_15
(
    is01_personkey bigint,
    is10_arbufoer_seq integer,
    is15_utbetfom_seq integer,
    is15_utbetfom integer,
    is15_utbettom integer,
    is15_utbetdato integer,
    is15_arbgivnr bigint,
    is15_bilag integer,
    is15_dsats numeric(9,2),
    is15_grad character(3)  ,
    is15_op character(2)  ,
    is15_type character(1)  ,
    is15_tilb_utbetdato integer,
    is15_tilb_bilag integer,
    is15_tilb_op character(2)  ,
    is15_tidskonto_kode character(1)  ,
    is15_brukerid character(7)  ,
    is15_regdato_batch integer,
    is15_tiltak_type character(2)  ,
    is15_korr character(4)  ,
    is15_aarsak_forskyv character(2)  ,
    is15_beregnet_i_os character(1)  ,
    tk_nr character(4),
    f_nr bigint DEFAULT 0,
    opprettet timestamp(6),
    endret_i_kilde timestamp(6),
    kilde_is varchar(12),
    region character(1),
    id_utbt double precision
);

-- is_periode_10 -------------
DROP TABLE IF EXISTS is_periode_10;
CREATE TABLE is_periode_10
(
    is01_personkey bigint DEFAULT 0,
    is10_arbufoer_seq integer,
    is10_arbufoer integer,
    is10_arbkat character(2)  ,
    is10_stat character(1)  ,
    is10_arbufoer_tom integer,
    is10_arbufoer_oppr integer,
    is10_ufoeregrad character(3)  ,
    is10_revurdert_dato integer,
    is10_aarsak_forskyv2 character(2)  ,
    is10_stoenads_type character(2)  ,
    is10_reg_dato_smii integer,
    is10_endr_dato_stat integer,
    is10_ventetid character(1)  ,
    is10_instopph_fom character(8)  ,
    is10_instopph_tom character(8)  ,
    is10_behdato integer,
    is10_kode_lege_inst character(1)  ,
    is10_legenr character(11)  ,
    is10_legenavn character(25)  ,
    is10_sykm_ii_dato integer,
    is10_prognosegruppe character(1)  ,
    is10_unntak character(1)  ,
    is10_uker_ventetid character(3)  ,
    is10_behandling character(1)  ,
    is10_melding_stat integer,
    is10_skadeart character(1)  ,
    is10_skdato integer,
    is10_skm_mott integer,
    is10_y_godkj character(1)  ,
    is10_ferie_fom integer,
    is10_ferie_tom integer,
    is10_fdato integer,
    is10_ant_barn character(1)  ,
    is10_morfnr bigint,
    is10_arbper character(1)  ,
    is10_yrke character(20)  ,
    is10_s_innt_dato integer,
    is10_spatest integer,
    is10_stans character(8)  ,
    is10_frisk character(1)  ,
    is10_regdat_frisk integer,
    is10_utbet_fom integer,
    is10_utbet_tom integer,
    is10_s_grad smallint,
    is10_frib_oppr_sald integer,
    is10_frib_saldo integer,
    is10_max integer,
    is10_tidsyk smallint,
    is10_tidsyk_kode character(1)  ,
    is10_saksblokk character(1)  ,
    is10_gruppe character(2)  ,
    is10_brukerid character(7)  ,
    is10_sak_framlegg character(1)  ,
    is10_feriedager_periode smallint,
    is10_feriedager_planlagt smallint,
    is10_stoenad_op_pb character(1)  ,
    is10_stoenad_om_sv character(1)  ,
    is10_innt_red_6g integer,
    is10_sak_type_o_s character(1)  ,
    is10_sak_prognosegrp character(1)  ,
    is10_dekningsgrad smallint,
    is10_ant_stoenadsdager smallint,
    is10_tidl_utbet integer,
    is10_tidl_utbet_k character(1)  ,
    is10_pros_inntekt_gr character(3)  ,
    is10_ant_barn_u_12aar character(2)  ,
    is10_aleneomsorg character(1)  ,
    is10_adopsjons_dato character(8)  ,
    is10_rett_til_fedrekvote character(1)  ,
    is10_fedrekvote character(1)  ,
    is10_fedrekvote_tom character(8)  ,
    is10_tidsyk_op_pb integer,
    is10_egenoppl character(1)  ,
    is10_antatt_sykm_tom character(8)  ,
    is10_vedtak_12_uker character(8)  ,
    is10_unntak_bs character(2)  ,
    is10_reg_dato character(8)  ,
    is10_stillingsandel_mor character(3)  ,
    is10_tidsk_type character(2)  ,
    is10_tidsk_barnfnr character(11)  ,
    is10_maxtidsk character(8)  ,
    is10_sammenfalende_periode character(1)  ,
    is10_sammenf_dager_mask character(3)  ,
    is10_diagnose_kode_1 character(1)  ,
    is10_diagnosegruppe character(6)  ,
    is10_diagnose character(70)  ,
    is10_diagnose_kode_2 character(1)  ,
    is10_diagnosegruppe_2 character(6)  ,
    is10_diagnose_2 character(70)  ,
    is10_termin_dato character(8)  ,
    is10_kjoep_helsetj character(2)  ,
    is10_helsetj_sendt character(8)  ,
    is10_utredet_operert character(1)  ,
    is10_utredet_operert_dato character(8)  ,
    is10_reg_dato_helsetj character(8)  ,
    is10_sammenheng_arb_sit character(1)  ,
    is10_arbeidstid_mor character(3)  ,
    is10_situasjon_mor character(1)  ,
    is10_rettighet_mor character(1)  ,
    is10_opphold_fom integer,
    is10_opphold_tom integer,
    is10_del2_type character(1)  ,
    is10_del2_regdato_j integer,
    is10_del2_regdato_u integer,
    is10_del2_dato integer,
    is10_friskm_dato integer,
    is10_svanger_syk character(1)  ,
    is10_paalogg_id character(7)  ,
    is10_unntak_aktivitet character(1)  ,
    is10_oppfolging_dato integer,
    is10_k68_dato integer,
    is10_k69_dato integer,
    is10_eos character(1)  ,
    is10_engang character(1)  ,
    is10_halv_hel character(1)  ,
    is10_k28_dato integer,
    is10_aarsak_forskyv character(2)  ,
    is10_stebarnsadopsjon character(1)  ,
    is10_surrogatmor character(1)  ,
    is10_dialog1_dato integer,
    is10_dialog1_kode character(1)  ,
    is10_dialog2_dato integer,
    is10_dialog2_kode character(1)  ,
    is10_oppfolging_kode character(1)  ,
    is10_k69a_dato integer,
    is10_polikl_beh character(8)  ,
    is10_arena_f234 character(1)  ,
    is10_avvent_sykmeld character(1)  ,
    is10_avvent_tom integer,
    is10_arena_f226 character(1)  ,
    is10_arbkat_99 character(2)  ,
    is10_pb_bekreft character(1)  ,
    is10_sanksjon_fom integer,
    is10_sanksjon_tom integer,
    is10_sanksjonsdager smallint,
    is10_sanksjon_bekreftet character(1)  ,
    is10_rett_til_modrekvote character(1)  ,
    is10_modrekvote character(1)  ,
    is10_modrekvote_tom character(8)  ,
    is10_ferie_fom2 integer,
    is10_ferie_tom2 integer,
    is10_stoppdato integer,
    tk_nr character(4),
    f_nr bigint DEFAULT 0,
    opprettet timestamp(6),
    endret_i_kilde timestamp(6),
    kilde_is character varying(12),
    region character(1),
    id_peri10 double precision DEFAULT 0
);


-- is_historikk_12
DROP TABLE IF EXISTS is_historikk_12;
CREATE TABLE is_historikk_12
(
    is01_personkey bigint NOT NULL,
    is10_arbufoer_seq integer NOT NULL,
    is12_segm_type character(1)   NOT NULL,
    is12_reg_dato_seq integer NOT NULL,
    is12_klokkeslett_seq character(6)   NOT NULL,
    is12_reg_dato integer NOT NULL,
    is12_klokkeslett character(6)   NOT NULL,
    is12_reg_ender_is10_dato integer NOT NULL,
    is12_ufoere_fom integer,
    is12_ufoere_tom integer,
    is12_ufoeregrad character(3)  ,
    is12_ufoeregrad_type character(1)  ,
    is12_hist_ufoer_brukerid character(7)  ,
    is12_kode_lege_inst character(1)  ,
    is12_legenr character(11)  ,
    is12_legenavn character(25)  ,
    is12_lege_fnr character(11)  ,
    is12_lege_fom integer,
    is12_lege_tom integer,
    is12_hist_lege_brukerid character(7)  ,
    is12_diagnose_kode_1 character(1)  ,
    is12_diagnosegruppe_1 character(6)  ,
    is12_diagnose_1 character(70)  ,
    is12_diagnose_kode_2 character(1)  ,
    is12_diagnosegruppe_2 character(6)  ,
    is12_diagnose_2 character(70)  ,
    is12_hist_diagnose_brukerid character(7)  ,
    is12_smii_reg_dato integer,
    is12_smii_prognosegr character(1)  ,
    is12_smii_unntak character(1)  ,
    is12_smii_dato integer,
    is12_hist_smii_brukerid character(7)  ,
    is12_unntak_kode character(1)  ,
    is12_unntak_brukerid character(7)  ,
    is12_diagnose_kode_bi character(1)  ,
    is12_diagnosegruppe_bi character(6)  ,
    is12_diagnose_bi character(70)  ,
    is12_hist_diagnose_bi_brukerid character(7)  ,
    is12_kjoep_helsetj character(2)  ,
    is12_helsetj_sendt character(8)  ,
    is12_utredet_operert character(1)  ,
    is12_utredet_operert_dato character(8)  ,
    is12_reg_dato_helsetj character(8)  ,
    is12_hist_helse_tj_brukerid character(7)  ,
    is12_del2_type character(1)  ,
    is12_del2_regdato_j character(8)  ,
    is12_del2_regdato_u character(8)  ,
    is12_del2_dato character(8)  ,
    is12_hist_del2_brukerid character(7)  ,
    is12_tiltak_fom integer,
    is12_tiltak_tom integer,
    is12_forl_periode_tom integer,
    is12_tiltak_type character(2)  ,
    is12_svanger_syk character(1)  ,
    is12_hist_svanger_brukerid character(7)  ,
    is12_brukerid character(7)  ,
    is12_oppflg_dialg_dato integer,
    is12_oppflg_dialg_kode character(1)  ,
    is12_oppflg_dialg_brukerid character(7)  ,
    tk_nr character(4)   NOT NULL,
    f_nr character(11)   NOT NULL,
    opprettet timestamp(6),
    endret_i_kilde timestamp(6),
    kilde_is character varying(12),
    region character(1),
    id_halt double precision NOT NULL
);

-- if_vedfrivt -------------
DROP TABLE IF EXISTS if_vedfrivt_10;
CREATE TABLE if_vedfrivt_10
(
    if01_kode character(1)   NOT NULL,
    if01_agnr_fnr bigint NOT NULL,
    if10_forsfom_seq integer NOT NULL,
    if10_godkj character(1)   NOT NULL,
    if10_forsfom integer NOT NULL,
    if10_virkdato integer NOT NULL,
    if10_type character(1)   NOT NULL,
    if10_selvfom character(4)   NOT NULL,
    if10_kombi character(1)   NOT NULL,
    if10_premgrl integer NOT NULL,
    if10_fom integer NOT NULL,
    if10_premie integer NOT NULL,
    if10_gml_premgrl integer NOT NULL,
    if10_gml_fom integer NOT NULL,
    if10_gml_premie integer NOT NULL,
    if10_frifom integer NOT NULL,
    if10_forstom integer NOT NULL,
    if10_opphgr character(10)   NOT NULL,
    if10_varsel integer NOT NULL,
    if10_term_kv character(1)   NOT NULL,
    if10_term_aar character(4)   NOT NULL,
    if10_varsel_beloep integer NOT NULL,
    if10_betalt_beloep integer NOT NULL,
    if10_purr integer NOT NULL,
    if10_tknr_bost smallint NOT NULL,
    if10_tknr_beh smallint NOT NULL,
    opprettet timestamp(6),
    endret_i_kilde timestamp(6),
    kilde_if character varying(12)   NOT NULL
);

-- if_vedfrivt -------------
DROP TABLE IF EXISTS is_diverse_11;
CREATE TABLE is_diverse_11
(
    is10_arbufoer_seq integer NOT NULL,
    is11_stlonn integer   NOT NULL,
    is11_natural numeric(11,2) NOT NULL,
    is11_utb_nat character(10) NOT NULL,
    is11_opph_nat integer   NOT NULL,
    is11_reduksj_beloep numeric(11,2) NOT NULL,
    is11_reduksj_type character(10) NOT NULL,
    is11_reduksj_fom integer   NOT NULL,
    is11_reduksj_tom integer   NOT NULL,
    f_nr character(11)   NOT NULL,
    opprettet timestamp(6),
    endret_i_kilde timestamp(6),
    kilde_if character varying(12)   NOT NULL
);
