create table T_DELYTELSE
(
    VEDTAK_ID       NUMBER           not null,
    TYPE_DELYTELSE  VARCHAR2(2 char) not null,
    TIDSPUNKT_REG   TIMESTAMP(6) default current_timestamp not null,
    FOM             DATE             not null,
    TOM             DATE,
    BELOP           NUMBER(11, 2)    not null,
    OPPGJORSORDNING CHAR(1 char),
    MOTTAKER_LOPENR NUMBER,
    BRUKERID        VARCHAR2(8 char) not null,
    TYPE_SATS       CHAR(1 char)     not null,
    TYPE_UTBETALING CHAR(1 char)     not null,
    LINJE_ID        NUMBER,
    OPPRETTET       TIMESTAMP(6) default current_timestamp,
    OPPDATERT       TIMESTAMP(6) default current_timestamp,
    DB_SPLITT       CHAR(2 char) default '  ',
    constraint PK_DELYTELSE
        primary key (VEDTAK_ID, TYPE_DELYTELSE, TIDSPUNKT_REG)
)
;

create table T_DELYTELSE_SP_FA_BS
(
    VEDTAK_ID        NUMBER            not null,
    TYPE_DELYTELSE   VARCHAR2(2 char)  not null,
    TIDSPUNKT_REG    TIMESTAMP(6) default current_timestamp not null,
    TYPE_INNTEKT     VARCHAR2(2 char)  not null,
    TYPE_TILTAK      VARCHAR2(2 char)  not null,
    TYPE_FORSIKRING  CHAR(1 char)      not null,
    PERIODE_KARENS   CHAR(1 char)      not null,
    PROSENT_INNT_GRL NUMBER            not null,
    ORGNR            VARCHAR2(9 char)  not null,
    REFUSJON         CHAR(1 char)      not null,
    GRAD             NUMBER            not null,
    DATO_MAX         DATE,
    KODE_KLASSE      VARCHAR2(20 char) not null,
    SATSENDRING      CHAR(1 char)      not null,
    DATO_ANNULLERT   DATE,
    SJOMANN          CHAR(1 char)      not null,
    TYPE_SATS        VARCHAR2(4 char)  not null,
    SATS_DAGER       NUMBER(7, 2)      not null,
    BRUKERID         VARCHAR2(8 char)  not null,
    OPPRETTET        TIMESTAMP(6) default current_timestamp,
    OPPDATERT        TIMESTAMP(6) default current_timestamp,
    DB_SPLITT        CHAR(2 char) default '  ',
    constraint PK_DELYT_SFB
        primary key (VEDTAK_ID, TYPE_DELYTELSE, TIDSPUNKT_REG)
)
;

create table T_LOPENR_FNR
(
    PERSON_LOPENR NUMBER            not null
        constraint PK_LOPENR_FNR
            primary key,
    PERSONNR      VARCHAR2(11 char) not null,
    OPPRETTET     TIMESTAMP(6) default current_timestamp,
    OPPDATERT     TIMESTAMP(6) default current_timestamp,
    DB_SPLITT     CHAR(2 char) default '  '
)
;

create table T_STONAD
(
    STONAD_ID         NUMBER       not null
        constraint PK_STONAD
            primary key,
    PERSON_LOPENR     NUMBER       not null,
    KODE_RUTINE       CHAR(2 char) not null,
    DATO_START        DATE         not null,
    KODE_OPPHOR       VARCHAR2(2 char),
    DATO_OPPHOR       DATE,
    OPPDRAG_ID        NUMBER,
    TIDSPUNKT_OPPHORT TIMESTAMP(6),
    TIDSPUNKT_REG     TIMESTAMP(6),
    BRUKERID          VARCHAR2(8 char),
    OPPRETTET         TIMESTAMP(6) default current_timestamp,
    OPPDATERT         TIMESTAMP(6) default current_timestamp,
    DB_SPLITT         CHAR(2 char) default '  '
)
;

create table T_VEDTAK
(
    VEDTAK_ID           NUMBER           not null
        constraint PK_VEDTAK
            primary key,
    PERSON_LOPENR       NUMBER           not null,
    KODE_RUTINE         CHAR(2 char)     not null,
    DATO_START          DATE             not null,
    TKNR                VARCHAR2(4 char) not null,
    SAKSBLOKK           CHAR(1 char)     not null,
    SAKSNR              NUMBER           not null,
    TYPE_SAK            VARCHAR2(2 char) not null,
    KODE_RESULTAT       VARCHAR2(2 char) not null,
    DATO_INNV_FOM       DATE             not null,
    DATO_INNV_TOM       DATE,
    DATO_MOTTATT_SAK    DATE             not null,
    KODE_VEDTAKSNIVAA   VARCHAR2(3 char) not null,
    TYPE_BEREGNING      VARCHAR2(3 char) not null,
    TKNR_BEH            VARCHAR2(4 char) not null,
    TIDSPUNKT_REG       TIMESTAMP(6) default current_timestamp not null,
    BRUKERID            VARCHAR2(8 char) not null,
    NOKKEL_DL1          VARCHAR2(30 char),
    ALTERNATIV_MOTTAKER NUMBER(11),
    STONAD_ID           NUMBER           not null,
    KIDNR               VARCHAR2(25 char),
    FAKTNR              VARCHAR2(33 char),
    OPPRETTET           TIMESTAMP(6) default current_timestamp,
    OPPDATERT           TIMESTAMP(6) default current_timestamp,
    DB_SPLITT           CHAR(2 char) default '  '
)
;

create table IS_PERIODE_10
(
    IS01_PERSONKEY             NUMBER(15)   default 0                 not null,
    IS10_ARBUFOER_SEQ          NUMBER(8)                              not null,
    IS10_ARBUFOER              NUMBER(8)                              not null,
    IS10_ARBKAT                CHAR(2 char)                           not null,
    IS10_STAT                  CHAR(1 char)                           not null,
    IS10_ARBUFOER_TOM          NUMBER(8)                              not null,
    IS10_ARBUFOER_OPPR         NUMBER(8)                              not null,
    IS10_UFOEREGRAD            VARCHAR2(3 char)                       not null,
    IS10_REVURDERT_DATO        NUMBER(8),
    IS10_AARSAK_FORSKYV2       CHAR(2 char),
    IS10_STOENADS_TYPE         CHAR(2 char),
    IS10_REG_DATO_SMII         NUMBER(8),
    IS10_ENDR_DATO_STAT        NUMBER(8),
    IS10_VENTETID              CHAR(1 char),
    IS10_INSTOPPH_FOM          VARCHAR2(8 char),
    IS10_INSTOPPH_TOM          VARCHAR2(8 char),
    IS10_BEHDATO               NUMBER(8),
    IS10_KODE_LEGE_INST        CHAR(1 char),
    IS10_LEGENR                VARCHAR2(11 char),
    IS10_LEGENAVN              VARCHAR2(25 char),
    IS10_SYKM_II_DATO          NUMBER(8),
    IS10_PROGNOSEGRUPPE        CHAR(1 char),
    IS10_UNNTAK                CHAR(1 char),
    IS10_UKER_VENTETID         VARCHAR2(3 char),
    IS10_BEHANDLING            CHAR(1 char),
    IS10_MELDING_STAT          NUMBER(8),
    IS10_SKADEART              CHAR(1 char),
    IS10_SKDATO                NUMBER(8),
    IS10_SKM_MOTT              NUMBER(8),
    IS10_Y_GODKJ               CHAR(1 char),
    IS10_FERIE_FOM             NUMBER(8),
    IS10_FERIE_TOM             NUMBER(8),
    IS10_FDATO                 NUMBER(8),
    IS10_ANT_BARN              CHAR(1 char),
    IS10_MORFNR                NUMBER(11),
    IS10_ARBPER                CHAR(1 char),
    IS10_YRKE                  VARCHAR2(20 char),
    IS10_S_INNT_DATO           NUMBER(8),
    IS10_SPATEST               NUMBER(8),
    IS10_STANS                 VARCHAR2(8 char),
    IS10_FRISK                 CHAR(1 char),
    IS10_REGDAT_FRISK          NUMBER(8),
    IS10_UTBET_FOM             NUMBER(8),
    IS10_UTBET_TOM             NUMBER(8),
    IS10_S_GRAD                NUMBER(3),
    IS10_FRIB_OPPR_SALD        NUMBER(5),
    IS10_FRIB_SALDO            NUMBER(7),
    IS10_MAX                   NUMBER(8),
    IS10_TIDSYK                NUMBER(3),
    IS10_TIDSYK_KODE           CHAR(1 char),
    IS10_SAKSBLOKK             CHAR(1 char),
    IS10_GRUPPE                CHAR(2 char),
    IS10_BRUKERID              VARCHAR2(7 char),
    IS10_SAK_FRAMLEGG          CHAR(1 char),
    IS10_FERIEDAGER_PERIODE    NUMBER(3),
    IS10_FERIEDAGER_PLANLAGT   NUMBER(3),
    IS10_STOENAD_OP_PB         CHAR(1 char),
    IS10_STOENAD_OM_SV         CHAR(1 char),
    IS10_INNT_RED_6G           NUMBER(7),
    IS10_SAK_TYPE_O_S          CHAR(1 char),
    IS10_SAK_PROGNOSEGRP       CHAR(1 char),
    IS10_DEKNINGSGRAD          NUMBER(3),
    IS10_ANT_STOENADSDAGER     NUMBER(3),
    IS10_TIDL_UTBET            NUMBER(8),
    IS10_TIDL_UTBET_K          CHAR(1 char),
    IS10_PROS_INNTEKT_GR       VARCHAR2(3 char),
    IS10_ANT_BARN_U_12AAR      CHAR(2 char),
    IS10_ALENEOMSORG           CHAR(1 char),
    IS10_ADOPSJONS_DATO        VARCHAR2(8 char),
    IS10_RETT_TIL_FEDREKVOTE   CHAR(1 char),
    IS10_FEDREKVOTE            CHAR(1 char),
    IS10_FEDREKVOTE_TOM        VARCHAR2(8 char),
    IS10_TIDSYK_OP_PB          NUMBER(5),
    IS10_EGENOPPL              CHAR(1 char),
    IS10_ANTATT_SYKM_TOM       VARCHAR2(8 char),
    IS10_VEDTAK_12_UKER        VARCHAR2(8 char),
    IS10_UNNTAK_BS             CHAR(2 char),
    IS10_REG_DATO              VARCHAR2(8 char),
    IS10_STILLINGSANDEL_MOR    VARCHAR2(3 char),
    IS10_TIDSK_TYPE            CHAR(2 char),
    IS10_TIDSK_BARNFNR         VARCHAR2(11 char),
    IS10_MAXTIDSK              VARCHAR2(8 char),
    IS10_SAMMENFALENDE_PERIODE CHAR(1 char),
    IS10_SAMMENF_DAGER_MASK    VARCHAR2(3 char),
    IS10_DIAGNOSE_KODE_1       CHAR(1 char),
    IS10_DIAGNOSEGRUPPE        VARCHAR2(6 char),
    IS10_DIAGNOSE              VARCHAR2(70 char),
    IS10_DIAGNOSE_KODE_2       CHAR(1 char),
    IS10_DIAGNOSEGRUPPE_2      VARCHAR2(6 char),
    IS10_DIAGNOSE_2            VARCHAR2(70 char),
    IS10_TERMIN_DATO           VARCHAR2(8 char),
    IS10_KJOEP_HELSETJ         CHAR(2 char),
    IS10_HELSETJ_SENDT         VARCHAR2(8 char),
    IS10_UTREDET_OPERERT       CHAR(1 char),
    IS10_UTREDET_OPERERT_DATO  VARCHAR2(8 char),
    IS10_REG_DATO_HELSETJ      VARCHAR2(8 char),
    IS10_SAMMENHENG_ARB_SIT    CHAR(1 char),
    IS10_ARBEIDSTID_MOR        VARCHAR2(3 char),
    IS10_SITUASJON_MOR         CHAR(1 char),
    IS10_RETTIGHET_MOR         CHAR(1 char),
    IS10_OPPHOLD_FOM           NUMBER(8),
    IS10_OPPHOLD_TOM           NUMBER(8),
    IS10_DEL2_TYPE             CHAR(1 char),
    IS10_DEL2_REGDATO_J        NUMBER(8),
    IS10_DEL2_REGDATO_U        NUMBER(8),
    IS10_DEL2_DATO             NUMBER(8),
    IS10_FRISKM_DATO           NUMBER(8),
    IS10_SVANGER_SYK           CHAR(1 char),
    IS10_PAALOGG_ID            VARCHAR2(7 char),
    IS10_UNNTAK_AKTIVITET      CHAR(1 char),
    IS10_OPPFOLGING_DATO       NUMBER(8),
    IS10_K68_DATO              NUMBER(8),
    IS10_K69_DATO              NUMBER(8),
    IS10_EOS                   CHAR(1 char),
    IS10_ENGANG                CHAR(1 char),
    IS10_HALV_HEL              CHAR(1 char),
    IS10_K28_DATO              NUMBER(8),
    IS10_AARSAK_FORSKYV        CHAR(2 char),
    IS10_STEBARNSADOPSJON      CHAR(1 char),
    IS10_SURROGATMOR           CHAR(1 char),
    IS10_DIALOG1_DATO          NUMBER(8),
    IS10_DIALOG1_KODE          CHAR(1 char),
    IS10_DIALOG2_DATO          NUMBER(8),
    IS10_DIALOG2_KODE          CHAR(1 char),
    IS10_OPPFOLGING_KODE       CHAR(1 char),
    IS10_K69A_DATO             NUMBER(8),
    IS10_POLIKL_BEH            VARCHAR2(8 char),
    IS10_ARENA_F234            CHAR(1 char),
    IS10_AVVENT_SYKMELD        CHAR(1 char),
    IS10_AVVENT_TOM            NUMBER(8),
    IS10_ARENA_F226            CHAR(1 char),
    IS10_ARBKAT_99             CHAR(2 char),
    IS10_PB_BEKREFT            CHAR(1 char),
    IS10_SANKSJON_FOM          NUMBER(8),
    IS10_SANKSJON_TOM          NUMBER(8),
    IS10_SANKSJONSDAGER        NUMBER(3),
    IS10_SANKSJON_BEKREFTET    CHAR(1 char),
    IS10_RETT_TIL_MODREKVOTE   CHAR(1 char),
    IS10_MODREKVOTE            CHAR(1 char),
    IS10_MODREKVOTE_TOM        VARCHAR2(8 char),
    IS10_FERIE_FOM2            NUMBER(8),
    IS10_FERIE_TOM2            NUMBER(8),
    IS10_STOPPDATO             NUMBER(8),
    TK_NR                      VARCHAR2(4)                            not null,
    F_NR                       VARCHAR2(11)                           not null,
    OPPRETTET                  TIMESTAMP(6) default current_timestamp not null,
    ENDRET_I_KILDE             TIMESTAMP(6) default current_timestamp not null,
    KILDE_IS                   VARCHAR2(12) default ' '               not null,
    REGION                     CHAR(1 char) default ' '               not null,
    ID_PERI10                  NUMBER
        constraint PK_IS_PERIODE_10
            primary key,
    OPPDATERT                  TIMESTAMP(6) default current_timestamp,
    DB_SPLITT                  CHAR(2 char) default '  '
)
;

create table IS_DIVERSE_11
(
    IS01_PERSONKEY      NUMBER(15)                                  not null,
    IS10_ARBUFOER_SEQ   NUMBER(8)                                   not null,
    IS11_STLONN         NUMBER(7)                                   not null,
    IS11_NATURAL        NUMBER(5, 2)                                not null,
    IS11_UTB_NAT        CHAR(1 char)                                not null,
    IS11_OPPH_NAT       NUMBER(8)                                   not null,
    IS11_REDUKSJ_BELOEP NUMBER(5, 2)                                not null,
    IS11_REDUKSJ_TYPE   CHAR(1 char)                                not null,
    IS11_REDUKSJ_FOM    NUMBER(8)                                   not null,
    IS11_REDUKSJ_TOM    NUMBER(8)                                   not null,
    TK_NR               VARCHAR2(4)                                 not null,
    F_NR                VARCHAR2(11)                                not null,
    OPPRETTET           TIMESTAMP(6)      default current_timestamp not null,
    ENDRET_I_KILDE      TIMESTAMP(6)      default current_timestamp not null,
    KILDE_IS            VARCHAR2(12 char) default ' '               not null,
    REGION              CHAR(1 char)      default ' '               not null,
    ID_DIV              NUMBER
        constraint PK_IS_DIVERSE
            primary key,
    OPPDATERT           TIMESTAMP(6)      default current_timestamp,
    DB_SPLITT           CHAR(2 char)      default '  '
)
;

create table IS_INNTEKT_13
(
    IS01_PERSONKEY      NUMBER(15)                             not null,
    IS10_ARBUFOER_SEQ   NUMBER(8)                              not null,
    IS13_SPFOM          NUMBER(8)                              not null,
    IS13_ARBGIVNR       NUMBER(11)                             not null,
    IS13_LOENN          NUMBER(11, 2)                          not null,
    IS13_PERIODE        CHAR(1 char)                           not null,
    IS13_REF            CHAR(1 char)                           not null,
    IS13_REF_TOM        NUMBER(8)                              not null,
    IS13_GML_SPFOM      NUMBER(8)                              not null,
    IS13_GML_LOENN      NUMBER(11, 2)                          not null,
    IS13_GML_PERIODE    CHAR(1 char)                           not null,
    IS13_PO_INNT        CHAR(1 char)                           not null,
    IS13_UTBET          CHAR(1 char)                           not null,
    IS13_TIDSKONTO_KODE CHAR(1 char)                           not null,
    TK_NR               VARCHAR2(4)                            not null,
    F_NR                VARCHAR2(11)                           not null,
    OPPRETTET           TIMESTAMP(6) default current_timestamp not null,
    ENDRET_I_KILDE      TIMESTAMP(6) default current_timestamp not null,
    KILDE_IS            VARCHAR2(12) default ' '               not null,
    REGION              CHAR(1 char) default ' '               not null,
    ID_INNT             NUMBER
        constraint PK_IS_INNTEKT
            primary key,
    OPPDATERT           TIMESTAMP(6) default current_timestamp,
    DB_SPLITT           CHAR(2 char) default '  '
)
;

create table IS_UTBETALING_15
(
    IS01_PERSONKEY      NUMBER(15)                              not null,
    IS10_ARBUFOER_SEQ   NUMBER(8)                               not null,
    IS15_UTBETFOM_SEQ   NUMBER(8)                               not null,
    IS15_UTBETFOM       NUMBER(8)                               not null,
    IS15_UTBETTOM       NUMBER(8)                               not null,
    IS15_UTBETDATO      NUMBER(8)                               not null,
    IS15_ARBGIVNR       NUMBER(11)                              not null,
    IS15_BILAG          NUMBER(7)                               not null,
    IS15_DSATS          NUMBER(9, 2)                            not null,
    IS15_GRAD           CHAR(3 char)                            not null,
    IS15_OP             CHAR(2 char)                            not null,
    IS15_TYPE           CHAR(1 char)                            not null,
    IS15_TILB_UTBETDATO NUMBER(8)                               not null,
    IS15_TILB_BILAG     NUMBER(7)                               not null,
    IS15_TILB_OP        CHAR(2 char)                            not null,
    IS15_TIDSKONTO_KODE CHAR(1 char)                            not null,
    IS15_BRUKERID       CHAR(7 char)                            not null,
    IS15_REGDATO_BATCH  NUMBER(8)                               not null,
    IS15_TILTAK_TYPE    CHAR(2 char)                            not null,
    IS15_KORR           CHAR(4 char)                            not null,
    IS15_AARSAK_FORSKYV CHAR(2 char)                            not null,
    IS15_BEREGNET_I_OS  CHAR(1 char)                            not null,
    TK_NR               CHAR(4)                                 not null,
    F_NR                CHAR(11)                                not null,
    OPPRETTET           TIMESTAMP(6)  default current_timestamp not null,
    ENDRET_I_KILDE      TIMESTAMP(6)  default current_timestamp not null,
    KILDE_IS            CHAR(12 char) default ' '               not null,
    REGION              CHAR(1 char)  default ' '               not null,
    ID_UTBT             NUMBER
        constraint PK_IS_UTBET
            primary key,
    OPPDATERT           TIMESTAMP(6)  default current_timestamp,
    DB_SPLITT           CHAR(2 char)  default 'SP'
)
;

create table IP_MERKNAD_20
(
    IP01_PERSNKEY       RAW(7)                                          not null,
    IP01_PERSONKEY      NUMBER(15)                                      not null,
    IP20_MERKNADS_KODE  NUMBER(3)                                       not null,
    IP20_MERKNAD_DATO1  NUMBER(8)                                       not null,
    IP20_MERKNAD_DATO2  NUMBER(8)                                       not null,
    IP20_MERKNAD_BELOP  NUMBER(9,2)                                     not null,
    IP20_BRUKERIDENT    VARCHAR2(7 char)                                not null,
    IP20_REG_DATO       VARCHAR2(8 char)                                not null,
    TK_NR               VARCHAR2(4)                                     not null,
    F_NR                VARCHAR2(11)                                    not null,
    OPPRETTET           TIMESTAMP(6)        default current_timestamp   not null,
    ENDRET_I_KILDE      TIMESTAMP(6)        default current_timestamp   not null,
    KILDE_IS            VARCHAR2(12 char)   default ' '                 not null,
    REGION              CHAR(1 char)        default ' '                 not null,
    ID_MERKN            NUMBER
        constraint PK_IP_MERKNAD
            primary key,
    OPPDATERT           TIMESTAMP(6)        default current_timestamp,
    DB_SPLITT           CHAR(2 char)        default '99'
)
