
package no.nav.tjeneste.virksomhet.ytelseskontrakt.v3;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-25T00:12:58.027Z
 * Generated source version: 3.1.6
 */

@WebFault(name = "hentYtelseskontraktListesikkerhetsbegrensning", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3")
public class HentYtelseskontraktListeSikkerhetsbegrensning extends Exception {
    
    private no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.feil.WSSikkerhetsbegrensning hentYtelseskontraktListesikkerhetsbegrensning;

    public HentYtelseskontraktListeSikkerhetsbegrensning() {
        super();
    }
    
    public HentYtelseskontraktListeSikkerhetsbegrensning(String message) {
        super(message);
    }
    
    public HentYtelseskontraktListeSikkerhetsbegrensning(String message, Throwable cause) {
        super(message, cause);
    }

    public HentYtelseskontraktListeSikkerhetsbegrensning(String message, no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.feil.WSSikkerhetsbegrensning hentYtelseskontraktListesikkerhetsbegrensning) {
        super(message);
        this.hentYtelseskontraktListesikkerhetsbegrensning = hentYtelseskontraktListesikkerhetsbegrensning;
    }

    public HentYtelseskontraktListeSikkerhetsbegrensning(String message, no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.feil.WSSikkerhetsbegrensning hentYtelseskontraktListesikkerhetsbegrensning, Throwable cause) {
        super(message, cause);
        this.hentYtelseskontraktListesikkerhetsbegrensning = hentYtelseskontraktListesikkerhetsbegrensning;
    }

    public no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.feil.WSSikkerhetsbegrensning getFaultInfo() {
        return this.hentYtelseskontraktListesikkerhetsbegrensning;
    }
}
