package no.nav.tjeneste.virksomhet.ytelseskontrakt.v3;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-25T00:12:58.028Z
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3", name = "Ytelseskontrakt_v3")
@XmlSeeAlso({no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.meldinger.ObjectFactory.class, no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.metadata.ObjectFactory.class, no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.feil.ObjectFactory.class, ObjectFactory.class, no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.informasjon.ytelseskontrakt.ObjectFactory.class})
public interface YtelseskontraktV3 {

    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3/Ytelseskontrakt_v3/pingRequest")
    @RequestWrapper(localName = "ping", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3", className = "no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3", className = "no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.PingResponse")
    public void ping();

    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3/Ytelseskontrakt_v3/hentYtelseskontraktListeRequest")
    @RequestWrapper(localName = "hentYtelseskontraktListe", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3", className = "no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.HentYtelseskontraktListe")
    @ResponseWrapper(localName = "hentYtelseskontraktListeResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseskontrakt/v3", className = "no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.HentYtelseskontraktListeResponse")
    @WebResult(name = "response", targetNamespace = "")
    public no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.meldinger.WSHentYtelseskontraktListeResponse hentYtelseskontraktListe(
        @WebParam(name = "request", targetNamespace = "")
        no.nav.tjeneste.virksomhet.ytelseskontrakt.v3.meldinger.WSHentYtelseskontraktListeRequest request
    ) throws HentYtelseskontraktListeSikkerhetsbegrensning;
}
