kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
limits:
  cpu: 2000m
azure:
  enabled: true
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    rules:
      - application: skjermede-personer-pip
        namespace: nom
env:
- name: SKJERMEDE_BASE_URL
  value: http://skjermede-personer-pip.nom.svc.cluster.local
- name: SKJERMEDE_OAUTH_SCOPE
  value: api://dev-gcp.nom.skjermede-personer-pip/.default