kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
azure:
  enabled: true
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    rules:
      - application: nom-api
        namespace: nom
env:
- name: SKJERMEDE_BASE_URL
  value: http://nom-api.nom.svc.cluster.local
- name: SKJERMEDE_OAUTH_SCOPE
  value: api://dev-gcp.nom.nom-api/.default