kafkaPool: nav-prod
azure:
  enabled: true
accessPolicy:
  outbound:
    rules:
      - application: nom-api
        namespace: nom
env:
- name: SKJERMEDE_BASE_URL
  value: http://nom-api.nom.svc.cluster.local
- name: SKJERMEDE_OAUTH_SCOPE
  value: api://prod-gcp.nom.nom-api/.default