kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkeldkif
env:
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: DKIF_URL
  value: http://dkif.default.svc.nais.local
