kafkaPool: nav-dev
replicas:
  min: "1"
  max: "1"
limits:
  cpu: 2000m
gcp:
  sqlInstances:
    - type: POSTGRES_15
      diskAutoresize: true
      databases:
        - name: sparkelstoppknapp
          envVarPrefix: DATABASE