kafkaPool: nav-prod
replicas:
  min: "1"
  max: "1"
limits:
  cpu: 2000m
env:
  - name: KAFKA_EXTRA_TOPIC
    value: teamsykefravr.apen-isyfo-stoppautomatikk
  - name: KAFKA_RESET_POLICY
    value: earliest