kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
limits:
  cpu: 2000m
azure:
  enabled: true
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    external:
      - host: oppgave.dev-fss-pub.nais.io
    rules:
      - application: speed-api
        namespace: tbd
env:
- name: OPPGAVE_URL
  value: https://oppgave.dev-fss-pub.nais.io
- name: OPPGAVE_SCOPE
  value: api://dev-fss.oppgavehandtering.oppgave/.default
