kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
accessPolicy:
  outbound:
    external:
      - host: oppgave.prod-fss-pub.nais.io
    rules:
      - application: speed-api
        namespace: tbd
env:
  - name: OPPGAVE_URL
    value: https://oppgave.prod-fss-pub.nais.io
  - name: OPPGAVE_SCOPE
    value: api://prod-fss.oppgavehandtering.oppgave/.default
