kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
azure:
  enabled: true
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    external:
      - host: kodeverk.dev-fss-pub.nais.io
      - host: aareg-services-q1.dev-fss-pub.nais.io
      - host: ereg-services-q1.dev-fss-pub.nais.io
env:
- name: KODEVERK_BASE_URL
  value: https://kodeverk.dev-fss-pub.nais.io/api
- name: ORGANISASJON_BASE_URL
  value: https://ereg-services-q1.dev-fss-pub.nais.io/api
- name: AAREG_BASE_URL_REST
  value: https://aareg-services-q1.dev-fss-pub.nais.io/api
- name: AAREG_OAUTH_SCOPE
  value: api://dev-fss.arbeidsforhold.aareg-services-nais-q1/.default
