kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
  allowAllUsers: false
  groups:
    - '611669fa-de5c-4dc2-a0e8-6041a019992a' # speil-brukere (vanlig saksbehandlertilgang)
    - 'c0227409-2085-4eb2-b487-c4ba270986a3' # nais-tbd
accessPolicy:
  inbound:
    rules:
      - application: speil
        namespace: tbd
        cluster: prod-gcp
  outbound:
    rules:
      - application: kodeverk-api
        namespace: team-rocket
    external:
      - host: aareg-services.prod-fss-pub.nais.io
      - host: ereg-services.prod-fss-pub.nais.io
env:
- name: KODEVERK_BASE_URL
  value: http://kodeverk-api.team-rocket
- name: KODEVERK_OAUTH_SCOPE
  value: api://prod-gcp.team-rocket.kodeverk-api/.default
- name: ORGANISASJON_BASE_URL
  value: https://ereg-services.prod-fss-pub.nais.io
- name: AAREG_BASE_URL_REST
  value: https://aareg-services.prod-fss-pub.nais.io
- name: AAREG_OAUTH_SCOPE
  value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default
