kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
accessPolicy:
  outbound:
    rules:
      - application: kodeverk-api
        namespace: team-rocket
    external:
      - host: aareg-services.prod-fss-pub.nais.io
      - host: ereg-services.prod-fss-pub.nais.io
env:
- name: KODEVERK_BASE_URL
  value: http://kodeverk-api.team-rocket
- name: KODEVERK_OAUTH_SCOPE
  value: api://prod-gcp.team-rocket.kodeverk-api/.default
- name: ORGANISASJON_BASE_URL
  value: https://ereg-services.prod-fss-pub.nais.io
- name: AAREG_BASE_URL_REST
  value: https://aareg-services.prod-fss-pub.nais.io
- name: AAREG_OAUTH_SCOPE
  value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default
