replicas:
  max: 24
cpu:
  max: 2000m
kafkaPool: nav-prod
mountPaths:
  - mountPath: /var/run/secrets/nais.io/oracle/creds
    kvPath: oracle/data/prod/creds/sp_infotrygd_p-user
  - mountPath: /var/run/secrets/nais.io/oracle/config
    kvPath: oracle/data/prod/config/infotrygd_spp
env:
- name: DATABASE_SCHEMA
  value: INFOTRYGD_SPP
onprem: true