replicas:
  min: 24
  max: 24
limits:
  cpu: 2000m
kafkaPool: nav-prod
mountPaths:
  - mountPath: /var/run/secrets/nais.io/oracle/creds
    kvPath: oracle/data/prod/creds/sp_infotrygd_p-user
  - mountPath: /var/run/secrets/nais.io/oracle/config
    kvPath: oracle/data/prod/config/infotrygd_spp
env:
- name: DATABASE_SCHEMA
  value: INFOTRYGD_SPP
- name: KAFKA_EXTRA_TOPIC
  value: tbd.teknisk.v1
onprem: true
