kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
limits:
  cpu: 2000m
azure:
  enabled: true
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    external:
      - host: inst2-q2.dev-fss-pub.nais.io
env:
  - name: INSTITUSJONSOPPHOLD_URL
    value: https://inst2-q2.dev-fss-pub.nais.io
  - name: INSTITUSJONSOPPHOLD_SCOPE
    value: api://dev-fss.team-rocket.inst2-q2/.default

