kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
accessPolicy:
  outbound:
    external:
      - host: inst2.prod-fss-pub.nais.io
env:
  - name: INSTITUSJONSOPPHOLD_URL
    value: https://inst2.prod-fss-pub.nais.io
  - name: INSTITUSJONSOPPHOLD_SCOPE
    value: api://prod-fss.team-rocket.inst2/.default
