kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
limits:
  cpu: 2000m
azure:
  enabled: true
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    external:
      - host: ikomp-q2.dev-fss-pub.nais.io
env:
  - name: INNTEKTSKOMPONENTEN_BASE_URL
    value: https://ikomp-q2.dev-fss-pub.nais.io/rs
  - name: INNTEKTSKOMPONENTEN_OAUTH_SCOPE
    value: api://dev-fss.team-inntekt.ikomp-q2/.default
