kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelinntekt
env:
- name: INNTEKTSKOMPONENT_BASE_URL
  value: https://app-q1.adeo.no/inntektskomponenten-ws/rs
