kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
accessPolicy:
  outbound:
    external:
      - host: team-inntekt-proxy.prod-fss-pub.nais.io
env:
  - name: INNTEKTSKOMPONENTEN_BASE_URL
    value: https://team-inntekt-proxy.prod-fss-pub.nais.io/proxy/inntektskomponenten/rs
  - name: INNTEKTSKOMPONENTEN_OAUTH_SCOPE
    value: api://prod-fss.team-inntekt.inntektskomponenten/.default
