kafkaPool: nav-prod
limits:
  cpu: 2000m
azure:
  enabled: true
accessPolicy:
  outbound:
    external:
      - host: ikomp.prod-fss-pub.nais.io
env:
  - name: INNTEKTSKOMPONENTEN_BASE_URL
    value: https://ikomp.prod-fss-pub.nais.io/rs
  - name: INNTEKTSKOMPONENTEN_OAUTH_SCOPE
    value: api://prod-fss.team-inntekt.ikomp/.default
