kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
cpu:
  max: 2000m
azure:
  enabled: true
envFrom:
  - sparkel-arena
accessPolicy:
  outbound:
    external:
      - host: ws-proxy.dev-fss-pub.nais.io
    rules:
      - application: ws-proxy
        namespace: tbd
        cluster: dev-fss
env:
- name: GANDALF_BASE_URL
  value: https://ws-proxy.dev-fss-pub.nais.io/gandalf
- name: WS_PROXY_SCOPE
  value: api://dev-fss.tbd.ws-proxy/.default
- name: YTELSESKONTRAKT_BASE_URL
  value: https://ws-proxy.dev-fss-pub.nais.io/arena/ail_ws/Ytelseskontrakt_v3
- name: MELDEKORT_UTBETALINGSGRUNNLAG_ENDPOINTURL
  value: https://ws-proxy.dev-fss-pub.nais.io/arena/ail_ws/MeldekortUtbetalingsgrunnlag_v1
