name: Aiven-config

on:
  push:
    branches:
      - main
    paths:
      - 'config/arbeidsgiver/aiven-dev.yml'
      - 'config/arbeidsgiver/aiven-prod.yml'

jobs:
  deployDev:
    name: apply kafka-topic i dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: config/arbeidsgiver/aiven-dev.yml

  deployProd:
    name: apply kafka-topic i prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: config/arbeidsgiver/aiven-prod.yml