name: Build
on:
  push:
    branches:
      - main
      - inntekt-i-skyen
env:
  CONTAINER_REGISTRY: europe-north1-docker.pkg.dev
  RESOURCE: config/nais.yml
  TEAM: tbd
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate_vars:
    runs-on: ubuntu-latest
    outputs:
      team: ${{ steps.set-vars.outputs.team }}
      tag: ${{ steps.set-vars.outputs.tag }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      deployMatrix: ${{ steps.set-matrix.outputs.deployMatrix }}
      emptyMatrix: ${{ steps.set-matrix.outputs.emptyMatrix }}
      emptyDeployMatrix: ${{ steps.set-matrix.outputs.emptyDeployMatrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: cache gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: cache gradle caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - id: set-vars
        name: create docker image SHA part
        run: |
          echo "team=$TEAM" >> $GITHUB_OUTPUT
          echo "tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - id: set-changed-files
        name: create CHANGED_FILES
        run: |
          # create a comma-separated list of changed files
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | tr '\r\n' ',' | sed -e 's/,$//')
          echo Endrede filer: $CHANGED_FILES
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
      - id: set-matrix
        name: create matrices
        run: |
          MATRIX=$(./gradlew -q buildMatrix --console=plain)
          DEPLOY_MATRIX=$(./gradlew -q deployMatrix --console=plain)
          MATRIX_SIZE=$(echo $MATRIX | jq '.project|length')
          DEPLOY_MATRIX_SIZE=$(echo $DEPLOY_MATRIX | jq '.project|length')

          if [ "$MATRIX_SIZE" == '0' ]; then
            echo "Empty matrix"
            echo "matrix=[]" >> $GITHUB_OUTPUT # to prevent error because matrix is empty
            echo "emptyMatrix=true" >> $GITHUB_OUTPUT
          else
            echo Setting matrix to $MATRIX
            echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
            echo "emptyMatrix=false" >> $GITHUB_OUTPUT
          fi
          if [ "$DEPLOY_MATRIX_SIZE" == '0' ]; then
            echo "Empty deploy matrix"
            echo "deployMatrix=[]" >> $GITHUB_OUTPUT # to prevent error because matrix is empty
            echo "emptyDeployMatrix=true" >> $GITHUB_OUTPUT
          else
            echo Setting deploy matrix to $DEPLOY_MATRIX
            echo "deployMatrix=$DEPLOY_MATRIX" >> $GITHUB_OUTPUT
            echo "emptyDeployMatrix=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: generate_vars
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    if: needs.generate_vars.outputs.emptyMatrix == 'false'
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate_vars.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.x'
      - name: cache gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: cache gradle caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: test and build
        run: ./gradlew ${{ matrix.project }}:test ${{ matrix.project }}:build
      - name: Check app.jar existence
        id: app_jar
        uses: andstor/file-existence-action@v2
        with:
          files: "${{ matrix.project }}/build/libs/app.jar"
      - name: build docker image
        if: steps.app_jar.outputs.files_exists == 'true'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{ needs.generate_vars.outputs.team }}
          image_suffix: ${{ matrix.project }}
          tag: ${{ needs.generate_vars.outputs.tag }}
          docker_context: ${{ matrix.project }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - run: |
          echo "Imagenavn: ${{ steps.docker-build-push.outputs.image }}"

  deploy:
    needs: [generate_vars, build]
    name: deploy
    if: always() && needs.generate_vars.outputs.emptyDeployMatrix == 'false'
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate_vars.outputs.deployMatrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: create env vars
        run: |
          # VARS og IMAGE er miljøvariabler som leses automatisk av nais/deploy/actions/deploy
          VARS_FILE="config/${{ matrix.project }}/${{ matrix.cluster }}.yml"
          echo "VARS=$VARS_FILE" >> $GITHUB_ENV
          echo "IMAGE=${{ env.CONTAINER_REGISTRY }}/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/${{ needs.generate_vars.outputs.team }}/${{ github.event.repository.name }}-${{ matrix.project }}:${{ needs.generate_vars.outputs.tag }}" >> $GITHUB_ENV
      - name: Fetch sources
        uses: actions/checkout@v3
      - name: Check for vars yml
        id: vars_file
        uses: andstor/file-existence-action@v2
        with:
          files: "${{ env.VARS }}"
      - name: deploy
        if: steps.vars_file.outputs.files_exists == 'true'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: ${{ matrix.cluster }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          VAR: team=${{ needs.generate_vars.outputs.team }},app=${{ matrix.project }}
